<?php $this->html( 'headelement' ); ?>

<div id="mw-js-message"></div>
<?php if ( $this->data['newtalk'] ): ?><div class="usermessage"><?php $this->html( 'newtalk' ); ?></div><?php endif; ?>
<?php if ( $this->data['sitenotice'] ): ?><div id="siteNotice"><?php $this->html( 'sitenotice' ) ?></div><?php endif; ?>

<div id="header1-wrapper">
	<div id="header1">
		<div id="header-social-links" class="social-links">
			<a target="_blank" class="facebook-link" href="http://www.banrepcultural.org/redes"></a>
			<a target="_blank" class="youtube-link" href="http://www.banrepcultural.org/redes"></a>
			<a target="_blank" class="instagram-link" href="http://www.banrepcultural.org/redes"></a>
			<a target="_blank" class="twitter-link" href="http://www.banrepcultural.org/redes"></a>
		</div>
		<div id="header-site-links">
			<a target="_blank" id="kids-link" href="http://www.banrepcultural.org/ninos-y-ninas">Para niños</a>
			<a target="_blank" id="accessibility-link" href="http://www.banrepcultural.org/accesibilidad">Accesibilidad</a>
			<a target="_blank" id="news-link" href="http://www.banrepcultural.org/noticias">Noticias</a>
			<a target="_blank" id="mail-link" href="http://www.banrepcultural.org/servicios/listas-de-correo">Listas de correo</a>
			<a target="_blank" id="register-link" href="http://www.banrepcultural.org/servicios/asociacion">Hazte socio</a>
		</div>
	</div>
</div>

<div id="header2-wrapper">
	<div id="header2">
		<a id="logo" href="<?php echo htmlspecialchars( $this->data['nav_urls']['mainpage']['href'] ); ?>"></a>
	</div>
</div>

<div id="header3-wrapper">
	<div id="header3">

		<form id="search-form" action="<?php $this->text( 'wgScript' ); ?>">
			<button type="submit"></button>
			<?php echo $this->makeSearchInput([ 'type' => 'text', 'id' => 'search-field', 'placeholder' => wfMessage( 'banrepcultural-search' ) ]); ?>
			<input type="hidden" name="title" value="<?php $this->text( 'searchtitle' ) ?>" />
		</form>

		<ul id="menu">
			<a id="home-icon" href="<?php echo htmlspecialchars( $this->data['nav_urls']['mainpage']['href'] ); ?>">
				<img src="<?= $images ?>home.png" />
			</a>

			<li><span><?php $this->text( 'sitename' ) ?></span>
				<ul class="submenu">
				<?php foreach ( $this->data['sidebar']['navigation'] as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</li>

			<li><span><?= wfMessage( 'banrepcultural-tools' ); ?></span>
				<ul class="submenu">
				<?php foreach ( $this->getToolbox() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</li>

			<?php if ( $actions ): ?>
			<li><span><?= wfMessage( 'banrepcultural-actions' ); ?></span>
				<ul class="submenu">
				<?php foreach ( $actions as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</li>
			<?php endif; ?>

			<li><span><?= wfMessage( 'banrepcultural-you' ); ?></span>
				<ul class="submenu">
				<?php foreach ( $this->getPersonalTools() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</li>
		</ul>

	</div>
</div>

<div id="content-wrapper">

	<div id="content">

		<?= $this->getIndicators(); ?>

		<h1 id="title"><?php $this->html( 'title' ) ?></h1>

		<?php if ( $this->data['subtitle'] ): ?>
		<div id="subtitle"><?php $this->html( 'subtitle' ) ?></div>
		<?php endif; ?>

		<?php if ( $this->data['undelete'] ): ?>
		<div id="undelete"><?php $this->html( 'undelete' ) ?></div>
		<?php endif; ?>

		<?php if ( $this->data['newtalk'] ): ?>
		<div class="newtalk"><?php $this->html( 'newtalk' )  ?></div>
		<?php endif; ?>

		<?php $this->html( 'bodytext' ) ?>

		<div class="printfooter"><?php $this->html( 'printfooter' ); ?></div>

		<?php $this->html( 'catlinks' ); ?>

		<?php $this->html( 'dataAfterContent' ); ?>

		<?php $this->html( 'debughtml' ); ?>

	</div>

</div>

<div id="footer-wrapper">
	<div id="footer">
		<div class="footer-column" id="footer-links">
			<img id="footer-icon" src="<?= $images ?>icon.png" />
			<ul>
				<li><a target="_blank" href="http://www.banrep.gov.co/">Banco de la República</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/acerca-de">Acerca de Banrepcultural</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/accesibilidad">Accesibilidad</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/noticias">Noticias</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/prensa">Sala de prensa</a></li>
				<li><a target="_blank" href="http://www.banrep.gov.co/es/transparencia-acceso-informacion-publica">Transparencia</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/servicios/preguntas-frecuentes">Ayuda</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/eform/submit/danos-tu-opinion">Danos tu opinión</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/derechos-de-autor">Derechos de autor</a></li>
				<li><a target="_blank" href="http://www.banrep.gov.co/atencion-ciudadano">Atención al ciudadano</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/creditos">Créditos</a></li>
				<li><br>
					<div class="social-links">
						<a target="_blank" class="facebook-link" href="http://www.banrepcultural.org/redes"></a>
						<a target="_blank" class="youtube-link" href="http://www.banrepcultural.org/redes"></a>
						<a target="_blank" class="instagram-link" href="http://www.banrepcultural.org/redes"></a>
						<a target="_blank" class="twitter-link" href="http://www.banrepcultural.org/redes"></a>
					</div>
				</li>
			</ul>
		</div>
		<div class="footer-column">
			<h4>Derechos de autor</h4>
			<p>Los contenidos están protegidos por los derechos de autor. Para más detalles ver <a href="#">derechos de autor</a>.</p>
			<h4>Sistema de atención al ciudadano</h4>
			<p>Si requiere realizar solicitudes de información, peticiones, quejas, reclamos, sugerencias, felicitaciones y denuncias, podrá realizarlas por medio de los canales oficiales establecidos en el Sistema de Atención al Ciudadano (SAC) del banco los cuales se presentan en la página web: <a href="#">Mecanismos para la atención al ciudadano</a>.</p>
			<a href="#">Buzón de notificaciones judiciales</a>
			<br>
			<a href="http://www.banrep.gov.co/proteccion-datos-personales">Políticas de protección de datos</a>
			<br>
			<a href="#">Políticas de seguridad</a>
		</div>
		<div class="footer-column">
			<h4>Subgerencia Cultural del Banco de la República</h4>
			<p>Bogotá<br>Biblioteca Luis Ángel Arango<br>Museos y colecciones del Banco de la República<br>Calle 11 # 4 - La Candelaria<br>571 343 1224<br>Fax 571 381 2908<br><a href="#">Horarios y oficinas</a></p>
			<p>La sección de divulgación de la Subgerencia Cultural es la responsable del desarrollo y mantenimiento de Banrepcultural</p>
		</div>
	</div>
</div>

<?php $this->printTrail(); ?>

</body>
</html>