<?php $this->html( 'headelement' ); ?>

<div id="mw-js-message"></div>
<?php if ( $this->data['newtalk'] ): ?><div class="usermessage"><?php $this->html( 'newtalk' ); ?></div><?php endif; ?>
<?php if ( $this->data['sitenotice'] ): ?><div id="siteNotice"><?php $this->html( 'sitenotice' ) ?></div><?php endif; ?>

<div id="header1-wrapper">
	<div id="header1">
		<div id="header-social-links" class="social-links">
			<a target="_blank" class="facebook-link" href="http://www.banrepcultural.org/redes"></a>
			<a target="_blank" class="youtube-link" href="http://www.banrepcultural.org/redes"></a>
			<a target="_blank" class="instagram-link" href="http://www.banrepcultural.org/redes"></a>
			<a target="_blank" class="twitter-link" href="http://www.banrepcultural.org/redes"></a>
		</div>
		<div id="header-site-links">
			<a target="_blank" id="kids-link" href="http://www.banrepcultural.org/ninos-y-ninas">Niñ@s</a>
			<a target="_blank" id="accessibility-link" href="http://www.banrepcultural.org/accesibilidad">Accesibilidad</a>
			<a target="_blank" id="news-link" href="http://www.banrepcultural.org/noticias">Noticias</a>
			<a target="_blank" id="mail-link" href="http://www.banrepcultural.org/servicios/listas-de-correo">Lista de correos</a>
			<a target="_blank" id="register-link" href="http://www.banrepcultural.org/servicios/asociacion">Hazte socio</a>
		</div>
	</div>
</div>

<div id="header2-wrapper">
	<div id="header2">
		<a id="logo" href="<?php echo htmlspecialchars( $this->data['nav_urls']['mainpage']['href'] ); ?>"></a>
	</div>
</div>

<div id="header3-wrapper">
	<div id="header3">

		<form id="search-form" action="<?php $this->text( 'wgScript' ); ?>">
			<button type="submit"></button>
			<?php echo $this->makeSearchInput([ 'type' => 'text', 'id' => 'search-field', 'placeholder' => wfMessage( 'banrepcultural-search' ) ]); ?>
			<input type="hidden" name="title" value="<?php $this->text( 'searchtitle' ) ?>" />
		</form>

		<ul id="menu">
			<a id="home-icon" href="<?php echo htmlspecialchars( $this->data['nav_urls']['mainpage']['href'] ); ?>">
				<img src="<?= $images ?>home.png" />
			</a>

			<?php foreach ( $this->data['sidebar'] as $menu => $items ): ?>
			<li><span><?php echo $menu; ?></span>
				<ul class="submenu">
				<?php foreach ( $items as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</li>
			<?php endforeach; ?>

			<li><span><?= wfMessage( 'banrepcultural-tools' ); ?></span>
				<ul class="submenu">
				<?php foreach ( $this->getToolbox() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</li>

			<?php if ( $actions ): ?>
			<li><span><?= wfMessage( 'banrepcultural-actions' ); ?></span>
				<ul class="submenu">
				<?php foreach ( $actions as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</li>
			<?php endif; ?>

			<li><span><?= wfMessage( 'banrepcultural-you' ); ?></span>
				<ul class="submenu">
				<?php foreach ( $this->getPersonalTools() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</li>
		</ul>

	</div>
</div>

<div id="content-wrapper">

	<div id="content">

		<?= $this->getIndicators(); ?>

		<h1 id="title"><?php $this->html( 'title' ) ?></h1>

		<?php if ( $this->data['subtitle'] ): ?>
		<div id="subtitle"><?php $this->html( 'subtitle' ) ?></div>
		<?php endif; ?>

		<?php if ( $this->data['undelete'] ): ?>
		<div id="undelete"><?php $this->html( 'undelete' ) ?></div>
		<?php endif; ?>

		<?php if ( $this->data['newtalk'] ): ?>
		<div class="newtalk"><?php $this->html( 'newtalk' )  ?></div>
		<?php endif; ?>

		<?php $this->html( 'bodytext' ) ?>

		<div class="printfooter"><?php $this->html( 'printfooter' ); ?></div>

		<?php $this->html( 'catlinks' ); ?>

		<?php $this->html( 'dataAfterContent' ); ?>

		<?php $this->html( 'debughtml' ); ?>

	</div>

</div>

<div id="footer-wrapper">
	<div id="footer">
		<div class="footer-column">
			<img id="footer-icon" src="<?= $images ?>icon.png" />
			<ul>
				<li><a target="_blank" href="http://www.banrepcultural.org/acerca-de">Acerca de Banrepcultural</a></li>
				<li><a target="_blank" href="http://www.banrep.gov.co/">Banco de la República</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/accesibilidad">Accesibilidad</a></li>
				<li><a target="_blank" href="http://www.banrep.gov.co/es/transparencia-acceso-informacion-publica">Transparencia</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/noticias">Noticias</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/prensa">Prensa</a></li>
				<li><a target="_blank" href="http://www.banrepcultural.org/servicios/publicaciones">Publicaciones</a></li>
				<li><br>
					<div class="social-links">
						<a target="_blank" class="facebook-link" href="http://www.banrepcultural.org/redes"></a>
						<a target="_blank" class="youtube-link" href="http://www.banrepcultural.org/redes"></a>
						<a target="_blank" class="instagram-link" href="http://www.banrepcultural.org/redes"></a>
						<a target="_blank" class="twitter-link" href="http://www.banrepcultural.org/redes"></a>
					</div>
				</li>
			</ul>
		</div>
		<div class="footer-column">
			<h2>Información de interés y ayuda</h2>
			<div><a href="/en">Versión en inglés</a></div>
			<div><a href="/servicios/preguntas-frecuentes">Preguntas frecuentes</a></div>
			<div><a href="/mapa-del-sitio">Mapa del sitio</a></div>
			<div><a href="/servicios/catalogo-bibliografico-en-linea">Catálogo en línea</a></div>
			<div><a href="/servicios/preguntas-frecuentes">Hazte socio</a></div>
			<div><a href="http://www.banrepcultural.org/boletin-cultural/">Boletín cultural y bibliográfico</a></div>
			<div><a href="/publicaciones">Derechos de Autor</a></div>
			<div><a href="/eform/submit/danos-tu-opinion">¿Encontraste algun error?</a></div>
			<div><a href="/creditos">Créditos</a></div>
		</div>
		<div class="footer-column">
			<h2>Contacto y avisos legales</h2>
			<div><a href="http://www.banrep.gov.co/donde-estamos">Localización física y horarios de atención al público en el territorio nacional</a></div>
			<div><a href="http://www.banrep.gov.co/atencion-ciudadano">Atención al ciudadano</a></div>
			<div><a href="https://atencionalciudadano.banrep.gov.co/siac/ess.do">Formulario electrónico de solicitudes de información</a></div>
			<div><a href="/servicios/listas-de-correo">Listas de correo</a></div>
			<div><a href="mailto: AtencionalCiudadano@banrep.gov.co">Contáctenos: atencionalciudadano@banrep.gov.co</a></div>
			<div><a href="http://www.banrep.gov.co/notificaciones-judiciales">Buzón de notificaciones judiciales</a></div>
			<div><a href="http://www.banrep.gov.co/aviso-legal">Aviso legal</a></div>
			<div><a href="http://www.banrep.gov.co/proteccion-datos-personales">Políticas de protección de datos personales</a></div>
			<div><a href="http://www.banrep.gov.co/politicas-de-seguridad-de-la-informacion">Políticas de seguridad de la información</a></div>
		</div>
		<div id="copyright">© 2017 Banco de la República, Colombia. Todos los derechos reservados.</div>
	</div>
</div>

<?php $this->printTrail(); ?>

</body>
</html>